import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const gramophone = localFont({
  src: [
    {
      path: '../public/fonts/Gramophone-Clean.woff',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-gramophone', // ایجاد متغیر CSS
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gramophone .variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
